name: cura-slicer
version: '4.6.2'
base: core20
summary: Ultimaker Cura
description: |
  Trusted by millions of users, Ultimaker Cura is the world’s most popular 3D printing software.
  Prepare prints with a few clicks, integrate with CAD software for an easier workflow, or dive into custom settings for in-depth control. 

  https://ultimaker.com/software/ultimaker-cura

  **Disclaimer:**

  This is not an official version of Cura! It is build from the release sources but depends an other runtime libraries (Ubuntu Core 18, etc.) than the official version.
  All product and company names are trademarks™ or registered® trademarks of their respective holders. Use of them does not imply any affiliation with or endorsement by them. 


architectures: 
  - amd64

grade: stable
confinement: strict

icon: snap/gui/cura-icon.png


plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes


apps:
  cura-engine:
    adapter: full
    command: usr/bin/CuraEngine
    plugs:
      - network
      - network-bind
      - netlink-connector
      - home
    
  cura:
    adapter: full
    command: usr/bin/cura
    command-chain:
      - bin/desktop-launch
      - bin/gtk3-env-launch
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.8:$PYTHONPATH
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
      DISABLE_WAYLAND: 1
      QT_QPA_PLATFORMTHEME: gtk3
    plugs:
      - desktop
      - unity7
      - wayland
      - mount-observe
      - network
      - network-bind
      - network-manager-observe
      - netlink-connector
      - home
      - opengl
      - removable-media
    

build-packages:
  - wget
  - qtbase5-dev
  - dpkg-dev
  - cmake
  - g++
  - protobuf-compiler
  - libprotobuf-dev
  - libprotoc-dev
  - libpython3-dev
  - python3-sip
  - python3-sip-dev
  - git
  - gettext
  - debhelper
  - dh-python
  - python3-all-dev
  - pylint
  - python3-pytest
  - python3-numpy
  - python3-setuptools
  - python3-wheel

parts:
  launchers: # custom launcher to set QT_QPA_PLATFORMTHEME=gtk3 correctly
    source: local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*


  patches:
    plugin: dump
    source: patches
    prime: [-*]


  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libgtk2.0-0
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
      - qt5-gtk-platformtheme


  libarcus:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DBUILD_PYTHON=ON
      - -DBUILD_EXAMPLES=OFF
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
    source-type: tar
    source: https://github.com/Ultimaker/libArcus/archive/4.6.2.tar.gz
    override-pull: |
      snapcraftctl pull
      patch -p1 < "/root/project/patches/Arcus/01-remove-rpath.patch"
      patch -p1 < "/root/project/patches/Arcus/02-add-python-version.patch"
      patch -p1 < "/root/project/patches/Arcus/0003-Allow-overriding-the-Python-version-in-CMake.patch"
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      mv ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/site-packages/* ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8
    stage-packages:
      - libprotobuf17
      - libpython3.8
      - libpolyclipping22


  libsavitar:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE-
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
    source-type: tar
    source: https://github.com/Ultimaker/libSavitar/archive/4.6.2.tar.gz
    build-packages:
      - libpugixml-dev
    stage-packages:
      - libpugixml1v5
    override-pull: |
      snapcraftctl pull
      patch -p1 < "/root/project/patches/Savitar/2001-remove-rpath.patch"
      patch -p1 < "/root/project/patches/Savitar/2002-system-pugixml.patch"
      patch -p1 < "/root/project/patches/Savitar/2003-remove-cmake-python-install-hack.patch"
      patch -p1 < "/root/project/patches/Savitar/2004-Allow-overriding-the-Python-version-in-CMake.patch"
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      mv ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/site-packages/* ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8
    after:
      - libarcus


  libcharon:
    plugin: cmake
    cmake-parameters: 
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
    source-type: tar
    source: https://github.com/Ultimaker/libCharon/archive/4.6.2.tar.gz
    stage-packages:
      - python3-urllib3
      - python3-certifi
    after:
      - libsavitar


  trimesh:
    plugin: python
    source-type: tar
    source: https://github.com/mikedh/trimesh/archive/3.7.10.tar.gz
    after:
      - libcharon
    override-build: |
      python3 setup.py --no-user-cfg install --prefix="${SNAPCRAFT_PART_INSTALL}/usr"
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      mv ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/site-packages/trimesh-3.7.10-py3.8.egg/trimesh ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8
    stage:
      -  -usr/bin/easy_install
      -  -usr/bin/f2py
      -  -usr/bin/f2py3
      -  -usr/bin/f2py3.8


  sentry-sdk:
    plugin: python
    source-type: tar
    source: https://github.com/getsentry/sentry-python/releases/download/0.16.1/sentry-sdk-0.16.1.tar.gz
    after:
      - trimesh
    override-build: |
      python3 setup.py --no-user-cfg install --prefix="${SNAPCRAFT_PART_INSTALL}/usr"
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      mv ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8/site-packages/sentry_sdk-0.16.1-py3.8.egg/sentry_sdk ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3/dist-packages
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/lib/python3.8
    stage:
      -  -usr/bin/easy_install
      -  -usr/bin/f2py
      -  -usr/bin/f2py3
      -  -usr/bin/f2py3.8


  cura-engine:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
      - -DUSE_SYSTEM_LIBS=ON
      - -Wno-dev
      - -DPolyclipping_INCLUDE_DIRS=/usr/include/polyclipping
    source-type: tar
    source: https://github.com/Ultimaker/CuraEngine/archive/4.6.2.tar.gz
    build-packages:
      - rapidjson-dev
      - libpolyclipping-dev
    stage-packages:
      - libgomp1
    override-pull: |
      snapcraftctl pull
      patch -p1 < "/root/project/patches/cura-engine/2000-remove-rpath.patch"
      patch -p1 < "/root/project/patches/cura-engine/2001-version-test.patch"
    after:
      - trimesh
    

  fdm-materials:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
    source-type: tar
    source: https://github.com/Ultimaker/fdm_materials/archive/4.6.2.tar.gz
    after: 
      - cura-engine


  uranium:
    plugin: cmake
    cmake-parameters: 
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
      - -DGETTEXT_MSGINIT_EXECUTABLE=msginit
      - -DGETTEXT_MSGMERGE_EXECUTABLE=msgmerge
      - -DCURA_BINARY_DATA_DIRECTORY=/usr/share/uranium
      - -DUM_NO_INSTALL_PLUGINS=UpdateChecker
    source-type: tar
    source: https://github.com/Ultimaker/Uranium/archive/4.6.2.tar.gz
    override-pull: |
      snapcraftctl pull
      patch -p1 < "/root/project/patches/uranium/uranium.patch"
    stage-packages:
      - python3-numpy
      - python3-scipy
      - python3-pyqt5
      - python3-serial
      - python3-pyqt5.qtopengl
      - python3-pyqt5.qtquick
      - python3-pyqt5.qtsvg
      - qml-module-qtqml-models2
      - qml-module-qtquick-dialogs
    after:
      - fdm-materials
      - patches
      - cura-engine
    stage:
      -  -usr/bin/f2py
      -  -usr/bin/f2py3
      -  -usr/bin/f2py3.8
  

  cura:
    plugin: cmake
    cmake-parameters: 
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr/
      - -DCMAKE_PREFIX_PATH="${SNAPCRAFT_STAGE}/usr"
      - -DURANIUM_DIR=${SNAPCRAFT_STAGE}/usr/share/uranium
      - -DCURA_VERSION=4.6.2
      - -DCURA_BUILDTYPE=SNAP
    source-type: tar
    source: https://github.com/Ultimaker/Cura/archive/4.6.2.tar.gz
    stage-packages:
      - fonts-open-sans
      - python3-cryptography
      - python3-colorlog
      - python3-requests
      - python3-shapely
      - python3-zeroconf
      - python3-distutils
      - python3-pyqt5.qtopengl
      - python3-pyqt5.qtquick
      - python3-pyqt5.qtsvg
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qt-labs-settings
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qtwayland5
    override-pull: |
      snapcraftctl pull
      patch -p1 < "/root/project/patches/cura/cura.patch"
    after:
      - desktop-qt5
      - uranium
      - patches
